//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EntityValidation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EntityValidation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EntityFramework.Web.Resources.EntityValidation", typeof(EntityValidation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ảnh banner.
        /// </summary>
        public static string AdvImg {
            get {
                return ResourceManager.GetString("AdvImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quảng cáo JS.
        /// </summary>
        public static string AdvScript {
            get {
                return ResourceManager.GetString("AdvScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhóm.
        /// </summary>
        public static string CateCode {
            get {
                return ResourceManager.GetString("CateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ảnh nhóm.
        /// </summary>
        public static string CategoryImage {
            get {
                return ResourceManager.GetString("CategoryImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nhóm chính.
        /// </summary>
        public static string CateMain {
            get {
                return ResourceManager.GetString("CateMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nhóm.
        /// </summary>
        public static string CateName {
            get {
                return ResourceManager.GetString("CateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm cha.
        /// </summary>
        public static string CateParent {
            get {
                return ResourceManager.GetString("CateParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm liên quan.
        /// </summary>
        public static string CateRefer {
            get {
                return ResourceManager.GetString("CateRefer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành phố.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo.
        /// </summary>
        public static string CompanyLogo {
            get {
                return ResourceManager.GetString("CompanyLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên công ty.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Năm thành lập.
        /// </summary>
        public static string CompanySince {
            get {
                return ResourceManager.GetString("CompanySince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nước.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên khách.
        /// </summary>
        public static string CustomerName {
            get {
                return ResourceManager.GetString("CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày tạo.
        /// </summary>
        public static string DateCreator {
            get {
                return ResourceManager.GetString("DateCreator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày xóa.
        /// </summary>
        public static string DateDeleted {
            get {
                return ResourceManager.GetString("DateDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sửa.
        /// </summary>
        public static string DateModify {
            get {
                return ResourceManager.GetString("DateModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nội dung chi tiết.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giảm giá.
        /// </summary>
        public static string Discount {
            get {
                return ResourceManager.GetString("Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiển thị.
        /// </summary>
        public static string Display {
            get {
                return ResourceManager.GetString("Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiển thị trang chủ.
        /// </summary>
        public static string DisplayOnHome {
            get {
                return ResourceManager.GetString("DisplayOnHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiển thị menu trái.
        /// </summary>
        public static string DisplayOnMenuLeft {
            get {
                return ResourceManager.GetString("DisplayOnMenuLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu chân trang.
        /// </summary>
        public static string DisplayOnMenuMain {
            get {
                return ResourceManager.GetString("DisplayOnMenuMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày hết hạn.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đầy đủ.
        /// </summary>
        public static string Fullname {
            get {
                return ResourceManager.GetString("Fullname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đối tượng thực hiện.
        /// </summary>
        public static string GroupIdList {
            get {
                return ResourceManager.GetString("GroupIdList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotline.
        /// </summary>
        public static string Hotline {
            get {
                return ResourceManager.GetString("Hotline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ảnh Thumbnail.
        /// </summary>
        public static string Img {
            get {
                return ResourceManager.GetString("Img", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ảnh Banner.
        /// </summary>
        public static string ImgBanner {
            get {
                return ResourceManager.GetString("ImgBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nổi bật.
        /// </summary>
        public static string IsHot {
            get {
                return ResourceManager.GetString("IsHot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin mới.
        /// </summary>
        public static string IsNews {
            get {
                return ResourceManager.GetString("IsNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chạy.
        /// </summary>
        public static string IsSale {
            get {
                return ResourceManager.GetString("IsSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ khóa.
        /// </summary>
        public static string Keyword {
            get {
                return ResourceManager.GetString("Keyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngôn ngữ.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá lớn.
        /// </summary>
        public static string MaxPrice {
            get {
                return ResourceManager.GetString("MaxPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meta data box.
        /// </summary>
        public static string MetaBox {
            get {
                return ResourceManager.GetString("MetaBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meta data description.
        /// </summary>
        public static string MetaDescription {
            get {
                return ResourceManager.GetString("MetaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meta data keyword.
        /// </summary>
        public static string MetaKeyword {
            get {
                return ResourceManager.GetString("MetaKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meta data robot tags.
        /// </summary>
        public static string MetaRobotTag {
            get {
                return ResourceManager.GetString("MetaRobotTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meta data title.
        /// </summary>
        public static string MetaTitle {
            get {
                return ResourceManager.GetString("MetaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá nhỏ.
        /// </summary>
        public static string MinPrice {
            get {
                return ResourceManager.GetString("MinPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm tin.
        /// </summary>
        public static string NewsCategories {
            get {
                return ResourceManager.GetString("NewsCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày đơn.
        /// </summary>
        public static string OrderDate {
            get {
                return ResourceManager.GetString("OrderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái đơn.
        /// </summary>
        public static string OrderStatus {
            get {
                return ResourceManager.GetString("OrderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biến tham số.
        /// </summary>
        public static string ParamKey {
            get {
                return ResourceManager.GetString("ParamKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị tham số.
        /// </summary>
        public static string ParamValue {
            get {
                return ResourceManager.GetString("ParamValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vị trí đặt banner.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá bán.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá bán hộ gia đình.
        /// </summary>
        public static string Price1 {
            get {
                return ResourceManager.GetString("Price1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá bán cơ quan, tổ chức.
        /// </summary>
        public static string Price2 {
            get {
                return ResourceManager.GetString("Price2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã hàng hóa.
        /// </summary>
        public static string ProductCode {
            get {
                return ResourceManager.GetString("ProductCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ảnh hàng hóa.
        /// </summary>
        public static string ProductImage {
            get {
                return ResourceManager.GetString("ProductImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên hàng hóa.
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slide 1.
        /// </summary>
        public static string ProductSlide1 {
            get {
                return ResourceManager.GetString("ProductSlide1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slide 2.
        /// </summary>
        public static string ProductSlide2 {
            get {
                return ResourceManager.GetString("ProductSlide2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slide 3.
        /// </summary>
        public static string ProductSlide3 {
            get {
                return ResourceManager.GetString("ProductSlide3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slide 4.
        /// </summary>
        public static string ProductSlide4 {
            get {
                return ResourceManager.GetString("ProductSlide4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slide 5.
        /// </summary>
        public static string ProductSlide5 {
            get {
                return ResourceManager.GetString("ProductSlide5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tác giả.
        /// </summary>
        public static string Publisher {
            get {
                return ResourceManager.GetString("Publisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tồn kho.
        /// </summary>
        public static string Quota {
            get {
                return ResourceManager.GetString("Quota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trường bắt buộc, không để trống.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ảnh dịch vụ.
        /// </summary>
        public static string ServiceImage {
            get {
                return ResourceManager.GetString("ServiceImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên dịch vụ.
        /// </summary>
        public static string ServiceName {
            get {
                return ResourceManager.GetString("ServiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày bắt đầu.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bang/Vùng.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiển thị.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đường phố.
        /// </summary>
        public static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuỗi quá dài, độ dài tối đa là {0}.
        /// </summary>
        public static string StringLengthTooLong {
            get {
                return ResourceManager.GetString("StringLengthTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nội dung tóm tắt.
        /// </summary>
        public static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách Tags.
        /// </summary>
        public static string TagsRefer {
            get {
                return ResourceManager.GetString("TagsRefer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiêu đề.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng.
        /// </summary>
        public static string Units {
            get {
                return ResourceManager.GetString("Units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đừng dẫn.
        /// </summary>
        public static string UrlAddress {
            get {
                return ResourceManager.GetString("UrlAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đường dẫn.
        /// </summary>
        public static string UrlText {
            get {
                return ResourceManager.GetString("UrlText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản tạo.
        /// </summary>
        public static string UserCreator {
            get {
                return ResourceManager.GetString("UserCreator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản xóa.
        /// </summary>
        public static string UserDeleted {
            get {
                return ResourceManager.GetString("UserDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản sửa.
        /// </summary>
        public static string UserModify {
            get {
                return ResourceManager.GetString("UserModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã vùng.
        /// </summary>
        public static string ZipCode {
            get {
                return ResourceManager.GetString("ZipCode", resourceCulture);
            }
        }
    }
}
